<?php

return [
    'guards' => ['web', 'api'],

    'permissions' => [
        'dashboard.view',

        'menu.dashboard.view',
        'menu.properties.view',
        'menu.zones.view',
        'menu.team-members.view',
        'menu.agencies.view',
        'menu.clients.view',
        'menu.property-contact-requests.view',
        'menu.calendar.view',
        'menu.users.view',
        'menu.rbac.view',
        'menu.easybroker.mls-export.view',
        'menu.mls.view',
        'menu.mls-agents.view',
        'menu.mls-offices.view',
        'menu.corporate-email.configuration.view',
        'menu.corporate-email.inbox.view',
        'menu.corporate-email.outbox.view',
        'menu.corporate-email.compose.view',
        'menu.cms.pages.view',
        'menu.cms.posts.view',
        'menu.cms.menus.view',
        'menu.cms.settings.view',
        'menu.tutorials.view',
        'menu.tutorial-videos.view',
        'menu.currencies.view',
        'menu.color-themes.view',
        'menu.frontend-colors.view',
        'menu.easybroker.view',
        'menu.notifications.view',

        'users.view',
        'users.view.all',
        'users.create',
        'users.edit',
        'users.deactivate',
        'users.delete',
        'users.export',

        'rbac.view',
        'rbac.manage',

        'properties.view',
        'properties.view.own',
        'properties.view.all',
        'properties.create',
        'properties.edit',
        'properties.edit.own',
        'properties.approve',
        'properties.publish',
        'properties.assign',
        'properties.status.update',
        'properties.delete',
        'properties.delete.own',
        'properties.restore',
        'properties.export',

        'leads.view',
        'leads.view.own',
        'leads.view.all',
        'leads.create',
        'leads.edit',
        'leads.edit.own',
        'leads.assign',
        'leads.status.update',
        'leads.delete',
        'leads.delete.own',
        'leads.restore',
        'leads.export',

        'clients.view',
        'clients.view.own',
        'clients.view.all',
        'clients.create',
        'clients.edit',
        'clients.edit.own',
        'clients.delete',
        'clients.restore',
        'clients.export',

        'crm.notes.view.own',
        'crm.notes.view.all',
        'crm.notes.create',
        'crm.notes.edit',
        'crm.notes.edit.own',
        'crm.notes.delete',
        'crm.notes.delete.own',

        'closings.view',
        'closings.view.own',
        'closings.view.all',
        'closings.create',
        'closings.edit',
        'closings.edit.own',
        'closings.approve',
        'closings.delete',
        'closings.export',

        'documents.view',
        'documents.view.own',
        'documents.view.all',
        'documents.create',
        'documents.edit',
        'documents.edit.own',
        'documents.delete',
        'documents.restore',
        'documents.export',

        'reports.view',
        'reports.view.global',
        'reports.export',

        'commissions.view',
        'commissions.view.own',
        'commissions.view.all',
        'commissions.edit',
        'commissions.approve',
        'commissions.export',

        'pipelines.view',
        'pipelines.view.own',
        'pipelines.view.all',
        'pipelines.edit',
        'pipelines.edit.own',

        'calendar.view',
        'calendar.view.own',
        'calendar.view.all',
        'calendar.edit',
        'calendar.edit.own',

        'notifications.view',
        'notifications.view.all',
        'notifications.manage',

        'corporate-email.view',
        'corporate-email.view.all',
        'corporate-email.send',
        'corporate-email.send.any',
        'corporate-email.accounts.manage',

        'cms.view',
        'cms.manage',

        'tutorials.view',
        'tutorials.manage',

        'catalogs.view',
        'catalogs.manage',

        'settings.view',
        'settings.manage',

        'integrations.view',
        'integrations.logs.view',
        'integrations.sync',
        'integrations.config.view',
        'integrations.config.edit',
        'integrations.manage',

        'marketing.view',
        'sensitive.view',
        'financial.view',
        'records.delete.critical',
    ],

    'roles' => [
        'super-admin' => [
            'label' => 'Administrador',
            'permissions' => '*',
        ],

        'manager' => [
            'label' => 'Manager',
            'permissions' => [
                'dashboard.view',

                'menu.dashboard.view',
                'menu.properties.view',
                'menu.zones.view',
                'menu.team-members.view',
                'menu.agencies.view',
                'menu.clients.view',
                'menu.property-contact-requests.view',
                'menu.calendar.view',
                'menu.easybroker.mls-export.view',
                'menu.mls.view',
                'menu.mls-agents.view',
                'menu.mls-offices.view',
                'menu.corporate-email.inbox.view',
                'menu.corporate-email.outbox.view',
                'menu.corporate-email.compose.view',
                'menu.cms.pages.view',
                'menu.cms.posts.view',
                'menu.cms.menus.view',
                'menu.cms.settings.view',
                'menu.tutorials.view',
                'menu.tutorial-videos.view',
                'menu.notifications.view',

                'properties.view',
                'properties.view.all',
                'properties.create',
                'properties.edit',
                'properties.approve',
                'properties.publish',
                'properties.assign',
                'properties.status.update',
                'properties.delete',
                'properties.restore',
                'properties.export',

                'leads.view',
                'leads.view.all',
                'leads.create',
                'leads.edit',
                'leads.assign',
                'leads.status.update',
                'leads.delete',
                'leads.restore',
                'leads.export',

                'clients.view',
                'clients.view.all',
                'clients.create',
                'clients.edit',
                'clients.delete',
                'clients.restore',

                'crm.notes.view.all',
                'crm.notes.create',

                'closings.view',
                'closings.view.all',
                'closings.create',
                'closings.edit',
                'closings.approve',
                'closings.delete',
                'closings.export',

                'documents.view',
                'documents.view.all',
                'documents.create',
                'documents.edit',
                'documents.delete',
                'documents.restore',

                'reports.view',
                'reports.view.global',

                'commissions.view',
                'commissions.view.all',

                'pipelines.view',
                'pipelines.view.all',
                'pipelines.edit',

                'calendar.view',
                'calendar.view.all',
                'calendar.edit',

                'notifications.view',
                'notifications.view.all',

                'corporate-email.view',
                'corporate-email.view.all',
                'corporate-email.send',
                'corporate-email.send.any',

                'cms.view',
                'tutorials.view',
                'tutorials.manage',
                'catalogs.view',
                'integrations.view',
                'integrations.logs.view',
                'integrations.sync',
                'marketing.view',
                'sensitive.view',
                'financial.view',
            ],
        ],

        'assistant' => [
            'label' => 'Asistente',
            'permissions' => [
                'dashboard.view',

                'menu.dashboard.view',
                'menu.properties.view',
                'menu.cms.pages.view',
                'menu.cms.posts.view',
                'menu.cms.menus.view',
                'menu.cms.settings.view',
                'menu.easybroker.view',
                'menu.tutorials.view',
                'menu.notifications.view',

                'properties.view',
                'properties.view.all',
                'properties.create',
                'properties.edit',
                'properties.status.update',
                'properties.delete',
                'properties.restore',
                'properties.export',

                'documents.view',
                'documents.view.all',
                'documents.create',
                'documents.edit',
                'documents.delete',
                'documents.restore',

                'cms.view',
                'cms.manage',
                'tutorials.view',
                'catalogs.view',
                'catalogs.manage',

                'notifications.view',

                'corporate-email.view',
                'corporate-email.send',

                'integrations.view',
                'integrations.logs.view',
                'integrations.sync',
            ],
        ],

        'agente' => [
            'label' => 'Agente',
            'permissions' => [
                'dashboard.view',

                'menu.dashboard.view',
                'menu.properties.view',
                'menu.clients.view',
                'menu.property-contact-requests.view',
                'menu.calendar.view',
                'menu.corporate-email.inbox.view',
                'menu.corporate-email.outbox.view',
                'menu.corporate-email.compose.view',
                'menu.tutorials.view',
                'menu.notifications.view',

                'properties.view',
                'properties.view.all',

                'leads.view',
                'leads.view.own',
                'leads.create',
                'leads.edit.own',
                'leads.status.update',
                'leads.delete.own',
                'leads.restore',

                'clients.view',
                'clients.view.own',
                'clients.create',
                'clients.edit.own',

                'crm.notes.view.own',
                'crm.notes.create',
                'crm.notes.edit.own',
                'crm.notes.delete.own',

                'closings.view',
                'closings.view.own',
                'closings.edit.own',

                'documents.view',
                'documents.view.own',
                'documents.create',
                'documents.edit.own',

                'pipelines.view',
                'pipelines.view.own',
                'pipelines.edit.own',

                'calendar.view',
                'calendar.view.own',
                'calendar.edit.own',

                'notifications.view',

                'corporate-email.view',
                'corporate-email.send',

                'tutorials.view',

                'commissions.view.own',
                'marketing.view',
            ],
        ],
    ],
];
