<?php

namespace App\Support;

final class ExpandedManualContent
{
    public static function articles(): array
    {
        return array_merge(
            self::inmobiliariaArticles(),
            self::crmArticles(),
            self::administrationArticles(),
            self::mlsArticles(),
            self::emailArticles(),
            self::cmsArticles(),
            self::settingsArticles(),
            self::internalHelpArticles(),
        );
    }

    private static function inmobiliariaArticles(): array
    {
        return [
            self::article('dashboard-referencia', 'Dashboard: lectura del resumen operativo', 'Interpreta los indicadores y accesos principales del inicio administrativo.', 'inmobiliaria', 10, 'menu.dashboard.view', 'dashboard',
                'Usar el dashboard como punto de partida para identificar actividad reciente y tareas pendientes.',
                ['Ingresa al panel con tu usuario.', 'Considera que los indicadores visibles dependen de tu rol.'],
                ['Abre Dashboard desde el menu lateral.', 'Revisa las tarjetas de resumen antes de iniciar tareas operativas.', 'Identifica accesos rapidos disponibles en la barra superior.', 'Consulta notificaciones si la campana muestra pendientes.', 'Abre el modulo relacionado cuando un indicador requiera revision.'],
                'Puedes decidir que modulo atender primero sin recorrer todas las pantallas.',
                recommendations: ['Usa el dashboard como resumen; confirma los detalles dentro del modulo correspondiente antes de modificar datos.']),
            self::article('propiedades-listado-filtros', 'Propiedades: listado, busqueda y filtros', 'Localiza inmuebles y revisa su estado desde el inventario.', 'inmobiliaria', 20, 'menu.properties.view', 'properties',
                'Encontrar rapidamente una propiedad antes de crear, editar o revisar informacion.',
                ['Ten disponible al menos un dato de referencia: titulo, ubicacion, identificador o estado.'],
                ['Abre Propiedades.', 'Usa el campo de busqueda para localizar coincidencias.', 'Aplica los filtros disponibles para reducir el inventario.', 'Revisa estado, fuente e informacion principal de cada resultado.', 'Abre la propiedad correcta para consultar o editar.', 'Limpia los filtros cuando necesites recuperar el listado completo.'],
                'Trabajas sobre el inmueble correcto y reduces duplicados.',
                warnings: ['No crees un inmueble nuevo sin buscar primero variantes del titulo, direccion o identificador.'],
                recommendations: ['Combina busqueda y filtros cuando el inventario sea amplio.', 'Antes de editar, confirma si la propiedad es local o proviene de una integracion.']),
            self::article('propiedades-editor-pestanas', 'Propiedades: estructura completa del editor', 'Recorre las pestanas del formulario sin omitir informacion importante.', 'inmobiliaria', 30, 'menu.properties.view', 'properties',
                'Comprender como se organiza la ficha de una propiedad y en que orden conviene completarla.',
                ['Abre una propiedad existente o selecciona Nueva propiedad.', 'Reune la informacion comercial y visual disponible.'],
                ['Completa primero los datos generales y el estado.', 'Revisa la fuente y los identificadores externos cuando apliquen.', 'Configura operaciones, precios y moneda.', 'Registra ubicacion y caracteristicas.', 'Carga portada, galeria y documentos.', 'Selecciona features y tags.', 'Guarda y vuelve a revisar la ficha completa.'],
                'La propiedad conserva una ficha coherente para operacion interna y publicacion.',
                warnings: ['Una ficha guardada no necesariamente esta lista para publicar. Revisa todos los grupos antes de cambiar su estado.'],
                recommendations: ['Completa el formulario en el orden de las pestanas para detectar faltantes con facilidad.']),
            self::article('propiedades-fuente-identificadores', 'Propiedades: fuente e identificadores externos', 'Distingue registros locales, MLS y EasyBroker antes de editarlos.', 'inmobiliaria', 40, 'menu.properties.view', 'properties',
                'Evitar duplicados y modificaciones incompatibles con la fuente original del inmueble.',
                ['Localiza la propiedad desde el inventario.', 'Identifica si la informacion fue creada manualmente o sincronizada.'],
                ['Abre la propiedad.', 'Revisa la fuente registrada.', 'Consulta los identificadores externos disponibles.', 'Compara esos datos antes de crear otro inmueble.', 'Mantiene los identificadores sin alterarlos cuando provengan de una sincronizacion.', 'Usa el modulo de integracion para corregir datos que deban actualizarse desde el origen.'],
                'La trazabilidad del inmueble se mantiene estable entre sistemas.',
                warnings: ['No reemplaces un identificador MLS o EasyBroker para reutilizar una ficha existente.'],
                recommendations: ['Cuando detectes un posible duplicado, documenta ambos registros antes de decidir cual conservar.']),
            self::article('propiedades-operaciones-precios', 'Propiedades: operaciones, precios y moneda', 'Configura venta, renta y valores comerciales de forma consistente.', 'inmobiliaria', 50, 'menu.properties.view', 'properties',
                'Registrar valores que puedan mostrarse y compararse correctamente.',
                ['Confirma el tipo de operacion.', 'Verifica la moneda acordada para cada precio.'],
                ['Abre la seccion de operaciones y precios.', 'Activa solamente las operaciones aplicables.', 'Captura el monto correspondiente a cada operacion.', 'Selecciona la moneda correcta.', 'Revisa que el valor coincida con la informacion comercial aprobada.', 'Guarda y valida como aparece en la ficha.'],
                'La propiedad comunica condiciones comerciales claras.',
                warnings: ['No mezcles montos de monedas diferentes en una misma operacion.', 'No publiques precios provisionales sin confirmacion.'],
                recommendations: ['Cuando cambie un precio, registra la actualizacion inmediatamente para evitar compartir informacion obsoleta.']),
            self::article('propiedades-ubicacion-caracteristicas', 'Propiedades: ubicacion y caracteristicas', 'Completa datos territoriales y atributos utiles para busqueda.', 'inmobiliaria', 60, 'menu.properties.view', 'properties',
                'Permitir que usuarios internos y visitantes encuentren el inmueble mediante filtros relevantes.',
                ['Ten disponibles ciudad, zona y datos descriptivos correctos.', 'Confirma las caracteristicas fisicas del inmueble.'],
                ['Abre la seccion de ubicacion.', 'Selecciona region, ciudad y zona correctas.', 'Completa direccion y referencias segun la politica de publicacion.', 'Registra habitaciones, banos, estacionamientos, superficies y demas caracteristicas aplicables.', 'Revisa que los datos numericos usen la unidad esperada.', 'Guarda y comprueba la ficha publica cuando corresponda.'],
                'Los filtros del inventario y del sitio publico clasifican correctamente la propiedad.',
                warnings: ['No publiques datos de ubicacion sensibles cuando la ficha solo deba mostrar una referencia general.'],
                recommendations: ['Usa valores verificables y evita aproximaciones innecesarias en superficies o cantidades.']),
            self::article('propiedades-portada-galeria', 'Propiedades: portada, galeria y documentos', 'Organiza material visual y archivos de apoyo.', 'inmobiliaria', 70, 'menu.properties.view', 'properties',
                'Presentar la propiedad con recursos visuales ordenados y documentos pertinentes.',
                ['Prepara imagenes aprobadas y con calidad suficiente.', 'Confirma si los documentos son publicos o solamente internos.'],
                ['Abre la seccion multimedia de la propiedad.', 'Selecciona una imagen principal representativa.', 'Agrega imagenes complementarias a la galeria.', 'Ordena el material visual con una secuencia logica.', 'Adjunta documentos solamente cuando corresponda.', 'Guarda y revisa la vista final.'],
                'La ficha muestra una portada clara y una galeria util.',
                warnings: ['No cargues documentos confidenciales como material publico.', 'Evita usar imagenes duplicadas o de baja calidad como portada.'],
                recommendations: ['Coloca primero exteriores, espacios principales y despues detalles complementarios.']),
            self::article('propiedades-features-tags', 'Propiedades: features y tags', 'Clasifica inmuebles con atributos reutilizables.', 'inmobiliaria', 80, 'menu.properties.view', 'properties',
                'Mejorar filtros, busquedas y consistencia editorial mediante atributos controlados.',
                ['Revisa las caracteristicas confirmadas del inmueble.', 'Usa solamente etiquetas existentes cuando representen el concepto correcto.'],
                ['Abre la seccion de features y tags.', 'Selecciona los atributos que realmente aplican.', 'Evita repetir conceptos equivalentes.', 'Usa tags para clasificaciones editoriales o comerciales pertinentes.', 'Guarda los cambios.', 'Verifica que la propiedad aparezca en los filtros esperados.'],
                'La propiedad queda clasificada con criterios consistentes.',
                warnings: ['Agregar etiquetas indiscriminadamente reduce la utilidad de los filtros.'],
                recommendations: ['Mantiene una nomenclatura estable y solicita ajustes de catalogo cuando falte un concepto recurrente.']),
            self::article('zonas-seo-referencia', 'Zonas: contenido y SEO territorial', 'Mantiene paginas publicas de zonas con textos claros para cada idioma.', 'inmobiliaria', 90, 'menu.zones.view', 'zones',
                'Administrar las paginas territoriales utilizadas por el sitio publico.',
                ['Confirma region, ciudad y zona.', 'Prepara titulo, descripcion y metadatos aprobados.'],
                ['Abre Zonas.', 'Busca la zona existente antes de crear otra.', 'Revisa slug, ubicacion y estado.', 'Completa titulo y descripcion en los idiomas disponibles.', 'Registra meta titulo y meta descripcion.', 'Guarda los cambios.', 'Abre la pagina publica para confirmar el resultado.'],
                'La zona dispone de una pagina publica util para navegacion y buscadores.',
                warnings: ['No cambies el slug de una zona publicada sin considerar enlaces existentes.'],
                recommendations: ['Describe rasgos reales de la zona y evita duplicar el mismo texto en varias ubicaciones.']),
        ];
    }

    private static function crmArticles(): array
    {
        return [
            self::article('leads-listado-filtros-estados', 'Leads: listado, filtros y estados', 'Prioriza solicitudes comerciales y registra su avance.', 'crm', 10, 'menu.property-contact-requests.view', 'property-contact-requests',
                'Mantener una bandeja de leads ordenada para que cada solicitud tenga seguimiento.',
                ['Ingresa al modulo Leads.', 'Identifica los estados de trabajo definidos por el equipo.'],
                ['Revisa primero los leads recientes.', 'Usa busqueda y filtros para localizar solicitudes.', 'Abre el detalle de cada lead relevante.', 'Comprueba origen, propiedad relacionada y datos de contacto.', 'Actualiza el estado despues de cada avance.', 'Asigna responsable cuando tu perfil lo permita.'],
                'La bandeja refleja la situacion real de cada oportunidad.',
                warnings: ['No elimines un lead solo porque no responde de inmediato. Usa el estado correspondiente.'],
                recommendations: ['Registra los cambios de estado el mismo dia del contacto.']),
            self::article('crear-lead-manual-referencia', 'Leads: registro manual', 'Crea una oportunidad recibida por telefono, correo u otro canal.', 'crm', 20, 'menu.property-contact-requests.view', 'property-contact-requests',
                'Incorporar al CRM solicitudes que no llegaron automaticamente desde el sitio.',
                ['Confirma nombre y al menos un medio de contacto.', 'Reune el contexto comercial disponible.'],
                ['Abre Leads.', 'Selecciona la opcion para crear un lead manual.', 'Captura nombre, correo y telefono disponibles.', 'Registra origen y mensaje o contexto.', 'Relaciona una propiedad cuando exista interes especifico.', 'Asigna responsable si corresponde.', 'Guarda y confirma que aparezca en el listado.'],
                'La solicitud queda disponible para seguimiento junto con los leads automaticos.',
                warnings: ['Busca el contacto antes de registrarlo para evitar duplicados.'],
                recommendations: ['Incluye suficiente contexto para que otra persona pueda continuar la atencion.']),
            self::article('editar-convertir-lead', 'Leads: edicion y conversion a cliente', 'Actualiza la oportunidad y crea el expediente cuando avance.', 'crm', 30, 'menu.property-contact-requests.view', 'property-contact-requests',
                'Convertir una solicitud calificada en un cliente gestionable sin perder contexto.',
                ['Localiza el lead correcto.', 'Confirma que sus datos de contacto sean suficientes.'],
                ['Abre el lead.', 'Actualiza datos y estado con la informacion mas reciente.', 'Revisa propiedad relacionada, origen y notas disponibles.', 'Selecciona Convertir a cliente cuando el seguimiento ya requiera expediente.', 'Confirma la conversion.', 'Abre el cliente generado y completa informacion adicional.'],
                'El cliente conserva el origen comercial y puede recibir comentarios y visitas.',
                warnings: ['No conviertas varias veces el mismo contacto para representar seguimientos diferentes.'],
                recommendations: ['Convierte cuando necesites agenda, historial y seguimiento estable, no solamente por recibir un primer mensaje.']),
            self::article('clientes-listado-filtros', 'Clientes: listado y localizacion', 'Encuentra expedientes y revisa responsables antes de abrirlos.', 'crm', 40, 'menu.clients.view', 'clients',
                'Acceder rapidamente al cliente correcto y respetar el alcance asignado al usuario.',
                ['Ten disponible nombre, correo o telefono.', 'Considera que algunos perfiles solo visualizan clientes propios.'],
                ['Abre Clientes.', 'Usa la busqueda para localizar el expediente.', 'Revisa los resultados antes de seleccionar.', 'Confirma datos de contacto y responsable.', 'Abre el expediente correcto.', 'Si no aparece, revisa filtros y permisos antes de crear otro registro.'],
                'Trabajas sobre un solo expediente consistente por cliente.',
                warnings: ['No crees registros duplicados cuando el cliente ya existe con otra variante de nombre.'],
                recommendations: ['Busca tambien por correo o telefono cuando el nombre no produzca coincidencias claras.']),
            self::article('clientes-expediente-completo', 'Clientes: expediente, comentarios y visitas', 'Mantiene el historial operativo de cada contacto.', 'crm', 50, 'menu.clients.view', 'clients',
                'Centralizar datos, comentarios y visitas para dar continuidad al seguimiento comercial.',
                ['Abre el expediente del cliente correcto.', 'Confirma que tienes permiso para editar cuando necesites guardar cambios.'],
                ['Revisa los datos generales del cliente.', 'Actualiza informacion de contacto cuando sea necesario.', 'Agrega comentarios con hechos, acuerdos y siguientes pasos.', 'Edita o elimina comentarios solamente para corregir informacion.', 'Registra visitas con propiedad, fecha y detalle.', 'Actualiza el estado de una visita cuando cambie.', 'Guarda y revisa el historial resultante.'],
                'El expediente permite comprender el seguimiento sin depender de conversaciones externas.',
                warnings: ['No incluyas datos sensibles innecesarios en comentarios.', 'No borres historial valido para simplificar visualmente el expediente.'],
                recommendations: ['Escribe comentarios breves, fechados por el sistema y orientados al siguiente paso.']),
            self::article('agenda-calendario-mensual', 'Agenda: calendario mensual de visitas', 'Consulta, crea y actualiza citas inmobiliarias.', 'crm', 60, 'menu.calendar.view', 'calendar',
                'Coordinar visitas y evitar conflictos de agenda.',
                ['Confirma cliente, propiedad, fecha y hora.', 'Verifica disponibilidad antes de guardar.'],
                ['Abre Agenda.', 'Navega al mes correspondiente.', 'Revisa las visitas existentes.', 'Selecciona el dia o la accion para crear una visita.', 'Relaciona cliente y propiedad.', 'Captura fecha, hora y notas pertinentes.', 'Guarda la visita.', 'Abre una cita existente cuando necesites actualizarla.'],
                'La agenda mensual refleja compromisos vigentes y facilita la coordinacion.',
                warnings: ['No programes una visita sin confirmar cliente y propiedad.', 'Actualiza cancelaciones o cambios para liberar el horario.'],
                recommendations: ['Consulta el calendario antes de acordar una nueva hora con el cliente.']),
        ];
    }

    private static function administrationArticles(): array
    {
        return [
            self::article('usuarios-formulario-roles', 'Usuarios: formulario, roles y estado', 'Crea accesos individuales y mantiene responsabilidades correctas.', 'administracion', 10, 'menu.users.view', 'users',
                'Administrar cuentas internas sin otorgar capacidades innecesarias.',
                ['Realiza la tarea con autorizacion.', 'Confirma identidad, correo y funcion del integrante.'],
                ['Abre Usuarios.', 'Busca por nombre o correo antes de crear una cuenta.', 'Crea o abre el registro correspondiente.', 'Completa los datos requeridos.', 'Asigna el rol que corresponda a sus responsabilidades.', 'Guarda el usuario.', 'Desactiva accesos cuando ya no deban utilizarse.'],
                'Cada colaborador dispone de una cuenta propia y un rol adecuado.',
                warnings: ['No compartas una cuenta entre varias personas.', 'No asignes Administrador como solucion rapida a un permiso faltante.'],
                recommendations: ['Revisa periodicamente usuarios activos y desactiva accesos obsoletos.']),
            self::article('rbac-conceptos', 'Roles y permisos: conceptos esenciales', 'Comprende la diferencia entre menu, consulta y operacion.', 'administracion', 20, 'menu.rbac.view', 'rbac',
                'Modificar accesos con criterio y entender por que una opcion puede mostrarse o permanecer restringida.',
                ['Debes contar con autorizacion administrativa.', 'Identifica el rol que deseas revisar.'],
                ['Considera que un permiso de menu controla visibilidad.', 'Distingue permisos de consulta, creacion, edicion, eliminacion y acciones especiales.', 'Revisa si el alcance es propio o global.', 'Comprueba el conjunto completo antes de guardar.', 'Valida el resultado con un usuario del rol afectado.'],
                'Puedes diagnosticar accesos faltantes sin ampliar permisos de forma indiscriminada.',
                warnings: ['Mostrar un enlace no reemplaza el permiso operativo exigido por la accion.'],
                recommendations: ['Aplica el minimo acceso necesario para la responsabilidad real del perfil.']),
            self::article('rbac-administrar-roles', 'Roles y permisos: administrar roles', 'Ajusta perfiles reutilizables para grupos de usuarios.', 'administracion', 30, 'menu.rbac.view', 'rbac',
                'Mantener roles coherentes y faciles de auditar.',
                ['Documenta el cambio solicitado.', 'Identifica quienes usan el rol antes de modificarlo.'],
                ['Abre Roles y permisos.', 'Selecciona el rol.', 'Revisa sus permisos actuales.', 'Agrega o elimina capacidades puntuales.', 'Guarda los cambios.', 'Comprueba menus y operaciones con un usuario representativo.', 'Documenta el motivo cuando el ajuste tenga impacto amplio.'],
                'Los usuarios del rol reciben un conjunto consistente de capacidades.',
                warnings: ['Un cambio en un rol afecta a todas las cuentas asociadas.'],
                recommendations: ['Prefiere roles estables y evita crear variantes por cada usuario salvo necesidad real.']),
            self::article('rbac-administrar-permisos', 'Roles y permisos: revisar permisos individuales', 'Interpreta capacidades delicadas antes de habilitarlas.', 'administracion', 40, 'menu.rbac.view', 'rbac',
                'Evaluar permisos sensibles como eliminacion, publicacion, integraciones y configuracion.',
                ['Identifica la accion exacta requerida.', 'Confirma el nivel de responsabilidad del solicitante.'],
                ['Localiza el permiso relacionado con el modulo.', 'Distingue consulta de modificacion.', 'Revisa si existe una variante propia y otra global.', 'Evalua acciones sensibles como eliminar, publicar o sincronizar.', 'Asigna solamente la capacidad necesaria.', 'Guarda y valida el escenario concreto.'],
                'El acceso concedido resuelve la tarea sin ampliar innecesariamente el alcance.',
                warnings: ['Permisos globales, eliminaciones criticas e integraciones requieren revision especial.'],
                recommendations: ['Prueba el caso exacto que motivo el cambio y evita validar solamente la presencia del menu.']),
        ];
    }

    private static function mlsArticles(): array
    {
        return [
            self::article('mls-configuracion-conexion', 'MLS: configuracion y prueba de conexion', 'Verifica credenciales y disponibilidad antes de sincronizar.', 'integraciones', 10, 'menu.mls.view', 'mls',
                'Confirmar que la integracion MLS puede consultar informacion correctamente.',
                ['Solicita autorizacion antes de cambiar credenciales.', 'Ten disponible la configuracion valida del proveedor.'],
                ['Abre MLS.', 'Revisa los campos de configuracion visibles.', 'Confirma que las credenciales correspondan al entorno correcto.', 'Guarda cambios solamente cuando sean necesarios.', 'Ejecuta la prueba de conexion.', 'Lee el resultado antes de iniciar una sincronizacion.'],
                'La integracion queda lista para ejecutar procesos con una conexion validada.',
                warnings: ['No reemplaces credenciales funcionales sin respaldo.', 'No compartas claves en comentarios o capturas innecesarias.'],
                recommendations: ['Prueba la conexion despues de cualquier cambio de configuracion.']),
            self::article('mls-tipos-sincronizacion', 'MLS: tipos de sincronizacion', 'Selecciona el proceso adecuado para propiedades, agentes u oficinas.', 'integraciones', 20, 'menu.mls.view', 'mls',
                'Ejecutar solamente la sincronizacion necesaria y revisar su resultado.',
                ['Confirma que la conexion MLS funciona.', 'Identifica el catalogo que requiere actualizacion.'],
                ['Abre MLS.', 'Revisa fecha y resultado de ejecuciones previas.', 'Selecciona el proceso correspondiente.', 'Inicia la sincronizacion.', 'Espera a que finalice antes de repetir la accion.', 'Lee el resumen de elementos procesados.', 'Comprueba el modulo afectado.'],
                'El catalogo seleccionado refleja la informacion mas reciente disponible.',
                warnings: ['No ejecutes varios procesos repetidamente mientras uno sigue en curso.'],
                recommendations: ['Sincroniza el catalogo puntual cuando conozcas el alcance del cambio.']),
            self::article('mls-recuperacion-errores', 'MLS: diagnostico y recuperacion de errores', 'Interpreta fallos antes de reintentar una sincronizacion.', 'integraciones', 30, 'menu.mls.view', 'mls',
                'Resolver incidencias sin ocultar el problema mediante reintentos repetitivos.',
                ['Conserva el mensaje de error.', 'Identifica que proceso fallo y en que momento.'],
                ['Revisa el resultado mostrado por MLS.', 'Determina si el fallo corresponde a conexion, credenciales o datos recibidos.', 'Prueba la conexion cuando el error sea de acceso.', 'Corrige configuracion solamente si tienes valores confirmados.', 'Repite una sola vez el proceso afectado.', 'Verifica el catalogo resultante.', 'Escala el mensaje completo si el error persiste.'],
                'La incidencia queda corregida o documentada con informacion util para soporte.',
                warnings: ['No repitas sincronizaciones fallidas indefinidamente.', 'No borres catalogos para intentar resolver un error de conexion.'],
                recommendations: ['Registra proceso, hora y mensaje exacto al solicitar soporte.']),
            self::article('mls-agentes-referencia', 'MLS: catalogo de agentes', 'Consulta agentes sincronizados y ajustes internos permitidos.', 'integraciones', 40, 'menu.mls-agents.view', 'mls-agents',
                'Mantener identificables los agentes MLS relacionados con propiedades y contenido publico.',
                ['Ejecuta sincronizacion cuando necesites datos recientes.', 'Distingue datos externos de ajustes internos.'],
                ['Abre Agentes MLS.', 'Busca por nombre o identificador.', 'Revisa agencia relacionada, estado y datos disponibles.', 'Actualiza solamente campos administrables.', 'Guarda los ajustes.', 'Comprueba relaciones con propiedades o la vista publica cuando aplique.'],
                'El catalogo conserva correspondencia con MLS y ajustes locales validos.',
                warnings: ['No uses un agente existente para representar a otra persona.', 'No reemplaces identificadores externos.'],
                recommendations: ['Sincroniza primero cuando la diferencia pueda provenir del origen MLS.']),
            self::article('mls-oficinas-referencia', 'MLS: catalogo de oficinas', 'Consulta oficinas sincronizadas y su visibilidad.', 'integraciones', 50, 'menu.mls-offices.view', 'mls-offices',
                'Mantener oficinas MLS correctas para relaciones con agentes y presentacion publica.',
                ['Identifica la oficina por nombre o identificador.', 'Confirma si se requiere un ajuste local.'],
                ['Abre Agencias MLS.', 'Busca la oficina.', 'Revisa identificador, estado y datos de contacto.', 'Comprueba agentes relacionados.', 'Modifica solamente campos permitidos.', 'Guarda y verifica el resultado publico cuando corresponda.'],
                'Las oficinas MLS permanecen consistentes con sus relaciones y visibilidad.',
                warnings: ['No reemplaces identificadores para fusionar oficinas diferentes.'],
                recommendations: ['Documenta posibles duplicados antes de realizar cambios locales.']),
            self::article('mls-exportacion-filtros', 'MLS a EasyBroker: exportacion y filtros', 'Publica en EasyBroker propiedades seleccionadas desde MLS.', 'integraciones', 60, 'menu.easybroker.mls-export.view', 'easybroker.mls-export',
                'Exportar solamente propiedades revisadas y aptas para el canal de destino.',
                ['Confirma acceso a exportacion.', 'Verifica que la propiedad MLS tenga informacion suficiente.'],
                ['Abre Exportar MLS a EasyBroker.', 'Usa filtros para localizar las propiedades candidatas.', 'Revisa estado y datos principales.', 'Selecciona solamente los registros aprobados.', 'Inicia la exportacion.', 'Espera el resultado.', 'Revisa mensajes de exito o error por propiedad.'],
                'EasyBroker recibe un conjunto controlado de propiedades revisadas.',
                warnings: ['No exportes masivamente sin revisar filtros y seleccion.', 'No repitas una exportacion fallida sin leer su mensaje.'],
                recommendations: ['Procesa lotes manejables para facilitar la revision de resultados.']),
        ];
    }

    private static function emailArticles(): array
    {
        return [
            self::article('correos-configuracion-cuentas', 'Correos: configurar cuentas corporativas', 'Registra buzones y valida conexion de entrada y salida.', 'correos', 10, 'menu.corporate-email.configuration.view', 'corporate-email.configuration',
                'Mantener cuentas corporativas listas para consultar y enviar mensajes.',
                ['Ten disponibles servidor, puertos, usuario y credenciales correctas.', 'Confirma autorizacion para administrar buzones.'],
                ['Abre Configuracion en Correos.', 'Busca una cuenta existente antes de crearla.', 'Completa direccion y datos de conexion.', 'Registra valores de entrada y salida segun el proveedor.', 'Guarda la cuenta.', 'Ejecuta las pruebas disponibles.', 'Corrige cualquier error antes de usar el buzon.'],
                'La cuenta corporativa puede recibir y enviar correo desde el panel.',
                warnings: ['No compartas contrasenas fuera de los campos protegidos.', 'No cambies puertos o seguridad por ensayo sin confirmar la configuracion del proveedor.'],
                recommendations: ['Prueba recepcion y envio despues de modificar una cuenta.']),
            self::article('correos-bandeja-filtros', 'Correos: bandeja de entrada y filtros', 'Consulta mensajes recibidos y localiza conversaciones relevantes.', 'correos', 20, 'menu.corporate-email.inbox.view', 'corporate-email.inbox',
                'Revisar correo corporativo sin perder mensajes que requieren accion.',
                ['Confirma que la cuenta este configurada.', 'Ingresa con acceso a la bandeja.'],
                ['Abre Bandeja de entrada.', 'Selecciona la cuenta cuando exista mas de un buzon.', 'Actualiza o sincroniza la lista si necesitas mensajes recientes.', 'Usa filtros o busqueda para localizar un remitente o asunto.', 'Abre el mensaje.', 'Revisa contenido y adjuntos con precaucion.', 'Define el siguiente paso operativo.'],
                'Los mensajes relevantes quedan identificados para su atencion.',
                warnings: ['No abras adjuntos inesperados sin validar remitente y contexto.'],
                recommendations: ['Busca por remitente y asunto cuando una conversacion no aparezca entre los mensajes recientes.']),
            self::article('correos-salida-referencia', 'Correos: bandeja de salida', 'Comprueba mensajes enviados y diagnostica entregas pendientes.', 'correos', 30, 'menu.corporate-email.outbox.view', 'corporate-email.outbox',
                'Confirmar que los mensajes preparados desde el panel fueron procesados correctamente.',
                ['Ten disponible destinatario, asunto o fecha aproximada.'],
                ['Abre Bandeja de salida.', 'Selecciona la cuenta correspondiente.', 'Localiza el mensaje por destinatario o asunto.', 'Revisa fecha y estado.', 'Abre el detalle cuando necesites validar contenido.', 'Si aparece error, consulta el mensaje antes de reenviar.', 'Corrige la causa y repite solamente cuando corresponda.'],
                'Puedes distinguir mensajes enviados de incidencias que requieren correccion.',
                warnings: ['No reenvies repetidamente un mensaje sin confirmar su estado.'],
                recommendations: ['Verifica la bandeja de salida cuando un destinatario indique que no recibio el correo.']),
            self::article('correos-redaccion-campos', 'Correos: redactar un mensaje', 'Envia correos corporativos con destinatarios y contenido revisados.', 'correos', 40, 'menu.corporate-email.compose.view', 'corporate-email.compose',
                'Preparar mensajes claros desde una cuenta corporativa autorizada.',
                ['Confirma cuenta remitente y destinatarios.', 'Prepara asunto y contenido final.'],
                ['Abre Redactar.', 'Selecciona la cuenta desde la cual enviaras.', 'Captura destinatarios correctos.', 'Agrega copias solamente cuando sean necesarias.', 'Escribe un asunto descriptivo.', 'Redacta y revisa el mensaje.', 'Adjunta archivos pertinentes si la pantalla lo permite.', 'Envia y confirma el resultado.'],
                'El mensaje queda registrado en la salida de la cuenta correcta.',
                warnings: ['Revisa cuidadosamente destinatarios antes de enviar informacion sensible.', 'Evita adjuntar archivos innecesarios o desactualizados.'],
                recommendations: ['Usa asuntos concretos para facilitar busquedas posteriores.']),
            self::article('correos-diagnosticar-errores', 'Correos: diagnosticar errores de conexion o envio', 'Identifica la causa antes de modificar la cuenta.', 'correos', 50, 'menu.corporate-email.configuration.view', 'corporate-email.configuration',
                'Resolver incidencias de correo conservando configuracion verificable.',
                ['Conserva el mensaje de error.', 'Identifica si ocurre al consultar o al enviar.'],
                ['Revisa el estado de la cuenta.', 'Ejecuta la prueba relacionada con el fallo.', 'Comprueba servidor, puerto, seguridad, usuario y credencial.', 'Confirma si el proveedor exige una clave especifica de aplicacion.', 'Guarda cambios solamente con valores validados.', 'Prueba nuevamente recepcion o envio.', 'Documenta el error si persiste.'],
                'La cuenta vuelve a operar o la incidencia queda lista para escalamiento.',
                warnings: ['No desactives seguridad de conexion para evitar un error sin autorizacion.'],
                recommendations: ['Incluye cuenta afectada, tipo de prueba y mensaje exacto al solicitar soporte.']),
        ];
    }

    private static function cmsArticles(): array
    {
        return [
            self::article('cms-paginas-grupos-campos', 'CMS: editar paginas y grupos de campos', 'Actualiza textos publicos sin modificar la estructura del sitio.', 'cms', 10, 'menu.cms.pages.view', 'cms.pages',
                'Mantener vigente el contenido editorial de las paginas publicas.',
                ['Identifica la pagina y el idioma.', 'Prepara el texto aprobado antes de editar.'],
                ['Abre Paginas.', 'Selecciona la pagina correcta.', 'Revisa los grupos de campos disponibles.', 'Edita solamente los campos necesarios.', 'Comprueba titulo, texto, enlaces y llamados a la accion.', 'Guarda los cambios.', 'Abre la pagina publica y revisa el resultado.'],
                'La pagina publica muestra contenido actualizado sin alterar otros bloques.',
                warnings: ['No reemplaces textos en un idioma con contenido de otro.', 'No cambies enlaces sin comprobar el destino.'],
                recommendations: ['Realiza cambios acotados y revisa la vista publica despues de guardar.']),
            self::article('cms-repeaters-media', 'CMS: listas repetibles e imagenes', 'Ordena bloques repetidos y selecciona recursos multimedia.', 'cms', 20, 'menu.cms.pages.view', 'cms.pages',
                'Administrar secciones compuestas por tarjetas, imagenes u otros elementos repetibles.',
                ['Prepara imagenes y textos consistentes.', 'Identifica el orden editorial esperado.'],
                ['Abre la pagina correspondiente.', 'Localiza el grupo repetible.', 'Agrega, edita o retira elementos segun el contenido aprobado.', 'Selecciona recursos multimedia desde el administrador disponible.', 'Ordena los elementos.', 'Guarda.', 'Comprueba alineacion, textos y recursos en la pagina publica.'],
                'La seccion publica conserva una secuencia clara y recursos correctos.',
                warnings: ['Retirar un elemento puede eliminar contenido visible inmediatamente despues de guardar.'],
                recommendations: ['Mantiene longitud y proporcion visual consistentes entre elementos del mismo grupo.']),
            self::article('cms-posts-referencia', 'CMS: administrar publicaciones', 'Crea y edita entradas editoriales para el sitio.', 'cms', 30, 'menu.cms.posts.view', 'cms.posts',
                'Publicar contenido editorial con titulo, cuerpo y estado correctos.',
                ['Prepara texto, imagen y metadatos aprobados.', 'Confirma si el contenido debe quedar publicado o en preparacion.'],
                ['Abre Publicaciones.', 'Busca una entrada existente antes de crear otra.', 'Completa titulo, slug y contenido.', 'Selecciona imagen y metadatos disponibles.', 'Revisa el estado de publicacion.', 'Guarda.', 'Abre la vista publica y comprueba formato y enlaces.'],
                'La publicacion queda disponible con contenido y estado correctos.',
                warnings: ['No cambies el slug de una entrada publicada sin considerar enlaces existentes.'],
                recommendations: ['Revisa ortografia y vista movil antes de difundir el enlace.']),
            self::article('cms-menus-referencia', 'CMS: administrar menus publicos', 'Controla enlaces, etiquetas y orden de navegacion.', 'cms', 40, 'menu.cms.menus.view', 'cms.menus',
                'Mantener navegacion publica clara y sin enlaces rotos.',
                ['Define la ubicacion del menu.', 'Confirma etiqueta, destino y orden deseados.'],
                ['Abre Menus.', 'Selecciona el menu correcto.', 'Revisa los elementos actuales.', 'Agrega o edita enlaces necesarios.', 'Ordena los elementos segun prioridad.', 'Guarda.', 'Recorre el menu publico y prueba cada enlace modificado.'],
                'La navegacion conduce a destinos validos en el orden esperado.',
                warnings: ['No elimines enlaces sin confirmar si siguen siendo necesarios para acceder a una pagina.'],
                recommendations: ['Usa etiquetas breves y comprensibles para visitantes.']),
            self::article('cms-configuracion-general', 'CMS: configuracion general del sitio', 'Actualiza valores globales de contacto, redes y presentacion.', 'cms', 50, 'menu.cms.settings.view', 'cms.settings',
                'Mantener datos compartidos por varias paginas desde un unico punto.',
                ['Identifica el grupo de configuracion afectado.', 'Confirma el valor aprobado.'],
                ['Abre Configuracion CMS.', 'Selecciona el grupo correspondiente.', 'Localiza la clave que deseas modificar.', 'Actualiza solamente el valor necesario.', 'Guarda los cambios.', 'Revisa las paginas donde se utiliza.', 'Confirma que el idioma y formato sean correctos.'],
                'El sitio reutiliza valores globales actualizados de forma consistente.',
                warnings: ['Un valor global puede afectar varias paginas simultaneamente.'],
                recommendations: ['Documenta cambios de contacto, redes sociales y valores institucionales.']),
        ];
    }

    private static function settingsArticles(): array
    {
        return [
            self::article('monedas-catalogo-detalle', 'Ajustes: catalogo de monedas', 'Mantiene codigos, simbolos y formatos usados por propiedades.', 'ajustes', 10, 'menu.currencies.view', 'currencies',
                'Conservar un catalogo estable para mostrar valores comerciales correctamente.',
                ['Confirma codigo internacional, simbolo y nombre de la moneda.'],
                ['Abre Monedas.', 'Busca el codigo existente.', 'Crea una moneda solamente si no existe.', 'Revisa nombre, codigo y simbolo.', 'Guarda.', 'Abre una propiedad para confirmar que la moneda pueda seleccionarse.', 'Verifica como se muestra el precio.'],
                'Las propiedades usan monedas identificables y consistentes.',
                warnings: ['No reutilices un codigo existente para representar otra moneda.'],
                recommendations: ['Evita eliminar monedas relacionadas con propiedades existentes.']),
            self::article('temas-color-internos', 'Ajustes: temas de color del panel', 'Configura y activa apariencias para la interfaz administrativa.', 'ajustes', 20, 'menu.color-themes.view', 'color-themes',
                'Mantener una apariencia interna legible y coherente.',
                ['Define la paleta aprobada.', 'Ten referencias de contraste para texto y fondos.'],
                ['Abre Temas de color.', 'Revisa los temas disponibles.', 'Crea o abre el tema que deseas ajustar.', 'Modifica los colores necesarios.', 'Guarda.', 'Activa el tema cuando corresponda.', 'Recorre varias pantallas del panel para validar lectura.'],
                'El panel usa una paleta interna consistente y legible.',
                warnings: ['No actives una paleta sin revisar contraste en botones, textos y fondos.'],
                recommendations: ['Conserva al menos un tema funcional para volver a una configuracion conocida.']),
            self::article('colores-frontend-vistas', 'Ajustes: colores del sitio por vista', 'Modifica tokens visuales del frontend y revisa el alcance.', 'ajustes', 30, 'menu.frontend-colors.view', 'frontend-colors',
                'Controlar la identidad visual publica sin afectar legibilidad.',
                ['Confirma la paleta aprobada.', 'Identifica las vistas que deben cambiar.'],
                ['Abre Colores Frontend.', 'Selecciona la vista o grupo correspondiente.', 'Revisa valores actuales antes de editar.', 'Cambia solamente los tokens necesarios.', 'Guarda.', 'Recorre paginas publicas representativas.', 'Comprueba contraste, botones, enlaces y fondos.'],
                'El sitio publico refleja la paleta aprobada con lectura adecuada.',
                warnings: ['Un color puede reutilizarse en varios componentes.', 'No evalues solamente una pagina antes de dar por terminado el cambio.'],
                recommendations: ['Revisa escritorio y movil despues de ajustes amplios de color.']),
            self::article('colores-frontend-importar-exportar', 'Ajustes: importar y exportar colores frontend', 'Respalda paletas antes de aplicar cambios extensos.', 'ajustes', 40, 'menu.frontend-colors.view', 'frontend-colors',
                'Mover o restaurar configuraciones visuales de forma controlada.',
                ['Confirma el formato esperado.', 'Genera un respaldo antes de importar.'],
                ['Abre Colores Frontend.', 'Exporta la configuracion actual.', 'Conserva el archivo como respaldo.', 'Revisa el contenido que deseas importar.', 'Ejecuta la importacion.', 'Guarda o aplica los cambios segun la pantalla.', 'Revisa varias paginas publicas.'],
                'La paleta puede restaurarse y los cambios se aplican de forma verificable.',
                warnings: ['Una importacion puede reemplazar varios valores simultaneamente.'],
                recommendations: ['Nombra respaldos con fecha y motivo del cambio.']),
            self::article('easybroker-configuracion-sync', 'Ajustes: EasyBroker y sincronizacion', 'Configura la integracion, prueba conexion y ejecuta procesos controlados.', 'ajustes', 50, 'menu.easybroker.view', 'easybroker',
                'Mantener la integracion EasyBroker operativa y revisar el resultado de cada ejecucion.',
                ['Confirma autorizacion para sincronizar.', 'Ten credenciales validas cuando debas modificar configuracion.'],
                ['Abre EasyBroker Sync.', 'Revisa configuracion y ultima ejecucion.', 'Prueba la conexion cuando sea necesario.', 'Selecciona el proceso adecuado.', 'Inicia la sincronizacion.', 'Espera el resultado.', 'Revisa mensajes y comprueba las propiedades afectadas.'],
                'La sincronizacion se ejecuta con un resultado verificable.',
                warnings: ['No cambies credenciales funcionales sin respaldo.', 'No repitas procesos en curso.'],
                recommendations: ['Documenta mensajes de error completos antes de solicitar soporte.']),
            self::article('notificaciones-centro-filtros', 'Ajustes: centro de notificaciones', 'Consulta eventos, filtra pendientes y marca elementos revisados.', 'ajustes', 60, 'menu.notifications.view', 'notifications',
                'Mantener visibles solamente los eventos que todavia requieren atencion.',
                ['Ingresa con acceso a notificaciones.', 'Identifica el tipo de evento que deseas revisar.'],
                ['Abre Notificaciones.', 'Revisa primero los elementos no leidos.', 'Usa filtros cuando necesites localizar eventos anteriores.', 'Abre el detalle relacionado cuando exista.', 'Atiende la tarea en el modulo correspondiente.', 'Marca como leidos los avisos ya revisados.', 'Vuelve al listado para confirmar pendientes restantes.'],
                'El centro de notificaciones representa tareas realmente pendientes.',
                warnings: ['Marcar como leido no ejecuta la accion operativa relacionada.'],
                recommendations: ['Revisa la campana al comenzar la jornada y despues de procesos importantes.']),
        ];
    }

    private static function internalHelpArticles(): array
    {
        return [
            self::article('manual-editor-detallado', 'Manual: editar capitulos y articulos', 'Mantiene la guia escrita organizada, visible y relacionada con cada modulo.', 'ayuda-interna', 40, 'menu.manual-articles.view', 'manual-articles',
                'Actualizar la documentacion interna sin perder estructura ni control de acceso.',
                ['Prepara el texto revisado.', 'Identifica capitulo, permiso y modulo relacionado.'],
                ['Abre Administrar manual.', 'Crea o actualiza el capitulo si la navegacion lo requiere.', 'Selecciona un video tutorial opcional para el capitulo.', 'Crea o abre el articulo.', 'Completa titulo, resumen y contenido.', 'Selecciona el capitulo.', 'Asigna permiso y ruta relacionada cuando correspondan.', 'Ordena el articulo dentro del capitulo.', 'Guarda y revisa desde Manual de uso.'],
                'El equipo encuentra instrucciones escritas vigentes y adecuadas a su perfil.',
                warnings: ['No elimines capitulos con articulos asociados.', 'No asignes un permiso mas restrictivo que el necesario para consultar la guia.'],
                recommendations: ['Actualiza el manual en el mismo cambio operativo que modifica una pantalla.']),
            self::article('videos-editor-detallado', 'Videotutoriales: crear, ordenar y relacionar videos', 'Usa videos como apoyo visual del manual escrito.', 'ayuda-interna', 50, 'menu.tutorial-videos.view', 'tutorial-videos',
                'Mantener recursos visuales localizables sin duplicar la documentacion principal.',
                ['Ten disponible el enlace de YouTube y una descripcion breve.', 'Identifica el capitulo donde el video aporta valor.'],
                ['Abre Administrar videos.', 'Crea o edita el tutorial.', 'Completa titulo, descripcion y enlace.', 'Define orden y estado.', 'Guarda.', 'Abre Administrar manual.', 'Edita el capitulo pertinente y selecciona su video tutorial.', 'Revisa la reproduccion desde Tutoriales o Manual de uso.'],
                'El video aparece como complemento contextual de todos los articulos del capitulo.',
                warnings: ['No uses el video como unica fuente de instrucciones esenciales.'],
                recommendations: ['Mantiene videos breves y orientados a una tarea concreta.']),
        ];
    }

    private static function article(
        string $slug,
        string $title,
        string $summary,
        string $section,
        int $sortOrder,
        ?string $permission,
        ?string $route,
        string $objective,
        array $requirements,
        array $steps,
        string $result,
        array $warnings = [],
        array $errors = [],
        array $recommendations = []
    ): array {
        return compact(
            'slug',
            'title',
            'summary',
            'section',
            'sortOrder',
            'permission',
            'route',
            'objective',
            'requirements',
            'steps',
            'result',
            'warnings',
            'errors',
            'recommendations'
        ) + ['sort_order' => $sortOrder];
    }
}
